// This file is generated by Wails
// It bridges Go and TypeScript

import { Snippet } from './types';

export interface App {
  GetAllSnippets(): Promise<Snippet[]>;
  GetSnippet(id: string): Promise<Snippet>;
  SaveSnippet(snippet: Snippet): Promise<void>;
  DeleteSnippet(id: string): Promise<void>;
  SearchSnippets(query: string): Promise<Snippet[]>;
  CopyToClipboard(text: string): Promise<void>;
  ReloadSnippets(): Promise<void>;
}

declare global {
  interface Window {
    Go: any;
    runtime: {
      EventsEmit: (name: string, data?: any) => void;
      EventsOn: (name: string, callback: (data?: any) => void) => void;
      EventsOnMultiple: (name: string, callback: (data?: any) => void, maxCallbacks: number) => void;
      EventsOff: (name: string) => void;
      EventsOnce: (name: string, callback: (data?: any) => void) => void;
      LogPrint: (message: string) => void;
      WindowReload: () => void;
      WindowCenter: () => void;
      WindowSetTitle: (title: string) => void;
      WindowFullscreen: () => void;
      WindowUnfullscreen: () => void;
      WindowIsFullscreen: () => Promise<boolean>;
      WindowSetSize: (width: number, height: number) => Promise<void>;
      WindowGetSize: () => Promise<{ width: number; height: number }>;
      WindowSetMinSize: (width: number, height: number) => void;
      WindowSetMaxSize: (width: number, height: number) => void;
      WindowSetPosition: (x: number, y: number) => void;
      WindowGetPosition: () => Promise<{ x: number; y: number }>;
      WindowHide: () => void;
      WindowShow: () => void;
      WindowMaximise: () => void;
      WindowUnmaximise: () => void;
      WindowIsMaximised: () => Promise<boolean>;
      WindowMinimise: () => void;
      WindowUnminimise: () => void;
      WindowIsMinimised: () => Promise<boolean>;
      WindowSetBackgroundColour: (r: number, g: number, b: number, a: number) => void;
      ScreenGetAll: () => Promise<any[]>;
      BrowserOpenURL: (url: string) => void;
      ClipboardGetText: () => Promise<string>;
      ClipboardSetText: (text: string) => Promise<void>;
      Quit: () => void;
      Hide: () => void;
      Show: () => void;
      Environment: () => Promise<{ platform: string; arch: string; [key: string]: any }>;
    };
  }
}

// Wails will inject the app methods at runtime
export const app: App = window as any;
